In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm, metrics, preprocessing

In [2]:
train = pd.read_csv("bank-train.csv", header=None, sep=';')
train_headers = train.iloc[0]
train_df = pd.DataFrame(train.values[1:], columns=train_headers)


le = preprocessing.LabelEncoder()
le.fit(['admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management', 'retired', 'self-employed', 'services',
        'student', 'technician', 'unemployed', 'unknown'])
train_df['job'] = le.transform(train_df['job'])

le = preprocessing.LabelEncoder()
le.fit(['divorced', 'married', 'single', 'housemaid', 'unknown', 'retired'])
train_df['marital'] = le.transform(train_df['marital'])

le = preprocessing.LabelEncoder()
le.fit(['basic.4y', 'basic.6y', 'basic.9y', 'high.school', 'illiterate', 'professional.course', 'university.degree',
        'unknown'])
train_df['education'] = le.transform(train_df['education'])

le = preprocessing.LabelEncoder()
le.fit(['no', 'unknown', 'yes'])
train_df['default'] = le.transform(train_df['default'])

le = preprocessing.LabelEncoder()
le.fit(['no', 'unknown', 'yes'])
train_df['housing'] = le.transform(train_df['housing'])

le = preprocessing.LabelEncoder()
le.fit(['no', 'unknown', 'yes'])
train_df['loan'] = le.transform(train_df['loan'])

le = preprocessing.LabelEncoder()
le.fit(['cellular', 'telephone'])
train_df['contact'] = le.transform(train_df['contact'])

le = preprocessing.LabelEncoder()
le.fit(['mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'])
train_df['month'] = le.transform(train_df['month'])

le = preprocessing.LabelEncoder()
le.fit(['mon', 'tue', 'wed', 'thu', 'fri'])
train_df['day_of_week'] = le.transform(train_df['day_of_week'])

le = preprocessing.LabelEncoder()
le.fit(['failure', 'nonexistent', 'success'])
train_df['poutcome'] = le.transform(train_df['poutcome'])

for col in train_df.columns:
    if col == 'y':
        continue
    train_df[col] = pd.to_numeric(train_df[col])

/Users/kingsman/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (0,10,11,12,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
feature_cols = ['age', 'job', 'default', 'campaign', 'pdays', 
                'emp.var.rate', 'cons.conf.idx', 'nr.employed']
train_df[feature_cols].var()

0
age                109.039215
job                 12.957768
default              0.165483
campaign             7.730465
pdays            34921.458494
emp.var.rate         2.465393
cons.conf.idx       21.392348
nr.employed       5231.519236
dtype: float64

In [18]:
X = train_df[feature_cols]
y = train_df.y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01, random_state=1)

In [19]:
# y_test1 = y_test.sort_index(ascending=1)
# y_test1.to_csv(r'svm_y.csv')

In [20]:
svm_algo = svm.SVC(kernel='rbf')

#Train the model using the training sets
svm_algo.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = svm_algo.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

/Users/kingsman/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

Accuracy: 0.9030303030303031
              precision    recall  f1-score   support

          no       0.91      0.98      0.95       294
         yes       0.64      0.25      0.36        36

    accuracy                           0.90       330
   macro avg       0.78      0.62      0.65       330
weighted avg       0.88      0.90      0.88       330

In [21]:
train_result = pd.DataFrame(y_pred.tolist(), columns=['Label'])
train_result.index.name = 'ID'
train_result.index = X_test.index
# train_result1 = train_result.sort_index(ascending=1)
# train_result1.to_csv(r'svm_linear_result_train.csv')

In [22]:
test = pd.read_csv("bank-test.csv", header=None, sep=';')
test_headers = test.iloc[0]
test_df = pd.DataFrame(test.values[1:], columns=test_headers)

le = preprocessing.LabelEncoder()
le.fit(['admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management', 'retired', 'self-employed', 'services',
        'student', 'technician', 'unemployed', 'unknown'])
test_df['job'] = le.transform(test_df['job'])

le = preprocessing.LabelEncoder()
le.fit(['divorced', 'married', 'single', 'housemaid', 'unknown', 'retired'])
test_df['marital'] = le.transform(test_df['marital'])

le = preprocessing.LabelEncoder()
le.fit(['basic.4y', 'basic.6y', 'basic.9y', 'high.school', 'illiterate', 'professional.course', 'university.degree',
        'unknown'])
test_df['education'] = le.transform(test_df['education'])

le = preprocessing.LabelEncoder()
le.fit(['no', 'unknown', 'yes'])
test_df['default'] = le.transform(test_df['default'])

le = preprocessing.LabelEncoder()
le.fit(['no', 'unknown', 'yes'])
test_df['housing'] = le.transform(test_df['housing'])

le = preprocessing.LabelEncoder()
le.fit(['no', 'unknown', 'yes'])
test_df['loan'] = le.transform(test_df['loan'])

le = preprocessing.LabelEncoder()
le.fit(['cellular', 'telephone'])
test_df['contact'] = le.transform(test_df['contact'])

le = preprocessing.LabelEncoder()
le.fit(['mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'])
test_df['month'] = le.transform(test_df['month'])

le = preprocessing.LabelEncoder()
le.fit(['mon', 'tue', 'wed', 'thu', 'fri'])
test_df['day_of_week'] = le.transform(test_df['day_of_week'])

le = preprocessing.LabelEncoder()
le.fit(['failure', 'nonexistent', 'success'])
test_df['poutcome'] = le.transform(test_df['poutcome'])

test_df[feature_cols]

0    age  job  default campaign pdays emp.var.rate cons.conf.idx nr.employed
0     40    0        0        1   999          1.1         -36.4        5191
1     25    7        0        1   999          1.1         -36.4        5191
2     29    1        0        1   999          1.1         -36.4        5191
3     46    1        1        1   999          1.1         -36.4        5191
4     55    1        1        1   999          1.1         -36.4        5191
...   ..  ...      ...      ...   ...          ...           ...         ...
8241  34    8        0        1   999         -1.1         -50.8      4963.6
8242  38    3        0        1   999         -1.1         -50.8      4963.6
8243  29   10        0        1     9         -1.1         -50.8      4963.6
8244  73    5        0        1   999         -1.1         -50.8      4963.6
8245  46    1        0        1   999         -1.1         -50.8      4963.6

[8246 rows x 8 columns]

In [23]:
test_pred = svm_algo.predict(test_df[feature_cols])
test_result = pd.DataFrame(test_pred.tolist(), columns=['Label'])
test_result.index.name = 'ID'
test_result

     Label
ID
0       no
1       no
2       no
3       no
4       no
...    ...
8241    no
8242   yes
8243   yes
8244    no
8245    no

[8246 rows x 1 columns]

In [26]:
test_result.to_csv(r'svm_rbf.csv')